on: pull_request
  
jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - run: yarn install
      - name: tsc compile
        uses: icrawl/action-tsc@v1
        with:
          project: myTSReduxApp